# Site settings
title: "Núria Belloc"
description_short: "Shiatsu a Gràcia"
description: "El shiatsu és una eina de contacte entre persones, un procés en moviment constant i en continua evolució."

email: shiatsu.nbr@gmail.com
address: "c/ Sors, nº 10. Gràcia"
tel: (+34) 651 862 122

permalink: pretty
url: http://shiatsu.nuriabelloc.com
baseurl: ''
cdn: 'https://googledrive.com/host/0Bxwn2g3WSTbRfk1DVGpwbEl4dFA3ajFiTGFyZlA0WklGY3Izc0YtSHhVYncyVk01SzBibjQ'
analytics: 'UA-59689079-1'
timezone: Europe/Amsterdam

# Build settings
markdown: kramdown
layouts: _layouts
includes: _includes
sass:
  sass_dir: css/_sass
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Prose settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  ignore: ['_config.yml', '404.html', 'sitemap.xml', 'robots.txt', 'README.md', 'CNAME', '.gitignore', '.editorconfig', 'css', '_layouts', '_includes', 'feed.xml', 'favicon.ico']
  media: 'image'
  metadata:
    '':
      - name: "menu"
        field:
          element: "checkbox"
          label: "vols que aparegui al menú de la web?"
          help: "si està clickat apareixerà al menú"
          value: boolean
      - name: "description"
        field:
          element: "text"
          label: "Descripció de la pàgina"
          help: "serveix per al google, quan busquin"
          placeholder: "Descriu`amb una frase (o dos) la pàgina"
      - name: "permalink"
        field:
          element: "text"
          label: "La ruta de la pagina"
          help: "s'ha d'escriure sense http://shiatsu.nuriabelloc.com/ i acabat amb /"
          placeholder: "exemple/"
          type: text
